/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesbloquearRouteImport } from './routes/desbloquear'
import { Route as HoleritesRouteImport } from './routes/holerites'
import { Route as MesclarRouteImport } from './routes/mesclar'
import { Route as RemoverPrefixosRouteImport } from './routes/remover-prefixos'
import { Route as RenomearPorValorRouteImport } from './routes/renomear-por-valor'
import { Route as SequenciadorRouteImport } from './routes/sequenciador'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesbloquearRoute = DesbloquearRouteImport.update({
  id: '/desbloquear',
  path: '/desbloquear',
  getParentRoute: () => rootRouteImport,
} as any)
const HoleritesRoute = HoleritesRouteImport.update({
  id: '/holerites',
  path: '/holerites',
  getParentRoute: () => rootRouteImport,
} as any)
const MesclarRoute = MesclarRouteImport.update({
  id: '/mesclar',
  path: '/mesclar',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoverPrefixosRoute = RemoverPrefixosRouteImport.update({
  id: '/remover-prefixos',
  path: '/remover-prefixos',
  getParentRoute: () => rootRouteImport,
} as any)
const RenomearPorValorRoute = RenomearPorValorRouteImport.update({
  id: '/renomear-por-valor',
  path: '/renomear-por-valor',
  getParentRoute: () => rootRouteImport,
} as any)
const SequenciadorRoute = SequenciadorRouteImport.update({
  id: '/sequenciador',
  path: '/sequenciador',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desbloquear': typeof DesbloquearRoute
  '/holerites': typeof HoleritesRoute
  '/mesclar': typeof MesclarRoute
  '/remover-prefixos': typeof RemoverPrefixosRoute
  '/renomear-por-valor': typeof RenomearPorValorRoute
  '/sequenciador': typeof SequenciadorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desbloquear': typeof DesbloquearRoute
  '/holerites': typeof HoleritesRoute
  '/mesclar': typeof MesclarRoute
  '/remover-prefixos': typeof RemoverPrefixosRoute
  '/renomear-por-valor': typeof RenomearPorValorRoute
  '/sequenciador': typeof SequenciadorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desbloquear': typeof DesbloquearRoute
  '/holerites': typeof HoleritesRoute
  '/mesclar': typeof MesclarRoute
  '/remover-prefixos': typeof RemoverPrefixosRoute
  '/renomear-por-valor': typeof RenomearPorValorRoute
  '/sequenciador': typeof SequenciadorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desbloquear'
    | '/holerites'
    | '/mesclar'
    | '/remover-prefixos'
    | '/renomear-por-valor'
    | '/sequenciador'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desbloquear'
    | '/holerites'
    | '/mesclar'
    | '/remover-prefixos'
    | '/renomear-por-valor'
    | '/sequenciador'
  id:
    | '__root__'
    | '/'
    | '/desbloquear'
    | '/holerites'
    | '/mesclar'
    | '/remover-prefixos'
    | '/renomear-por-valor'
    | '/sequenciador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesbloquearRoute: typeof DesbloquearRoute
  HoleritesRoute: typeof HoleritesRoute
  MesclarRoute: typeof MesclarRoute
  RemoverPrefixosRoute: typeof RemoverPrefixosRoute
  RenomearPorValorRoute: typeof RenomearPorValorRoute
  SequenciadorRoute: typeof SequenciadorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desbloquear': {
      id: '/desbloquear'
      path: '/desbloquear'
      fullPath: '/desbloquear'
      preLoaderRoute: typeof DesbloquearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holerites': {
      id: '/holerites'
      path: '/holerites'
      fullPath: '/holerites'
      preLoaderRoute: typeof HoleritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesclar': {
      id: '/mesclar'
      path: '/mesclar'
      fullPath: '/mesclar'
      preLoaderRoute: typeof MesclarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remover-prefixos': {
      id: '/remover-prefixos'
      path: '/remover-prefixos'
      fullPath: '/remover-prefixos'
      preLoaderRoute: typeof RemoverPrefixosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renomear-por-valor': {
      id: '/renomear-por-valor'
      path: '/renomear-por-valor'
      fullPath: '/renomear-por-valor'
      preLoaderRoute: typeof RenomearPorValorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequenciador': {
      id: '/sequenciador'
      path: '/sequenciador'
      fullPath: '/sequenciador'
      preLoaderRoute: typeof SequenciadorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesbloquearRoute: DesbloquearRoute,
  HoleritesRoute: HoleritesRoute,
  MesclarRoute: MesclarRoute,
  RemoverPrefixosRoute: RemoverPrefixosRoute,
  RenomearPorValorRoute: RenomearPorValorRoute,
  SequenciadorRoute: SequenciadorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
